braune_digital_activity:
    doctrine_subscribing: true  #enable the direct creation of activities
    observed_classes:           #array of classes that need to be watched
        'AppBundle\Entity\TimedTask': #classname
            fields:                           #watched fields
              created: ~
              title: ~
              modified: ~
        'Application\Ekas\AppBundle\Entity\Step': ~ # watch creation / deletion only
        'AppBundle\Entity\TimedTask':
            fields:
                done: ~
                title: ~
                description: ~