#braune_digital_activity:
#    observed_classes:
#        -   name: Application\Sonata\UserBundle\Entity\User
#            fields:
#                - fieldName: picture
#                - fieldName: username
#                - fieldName: lastLogin
#        -   name: Application\AppBundle\Entity\Offer
#            fields:
#                - fieldName: icon
#                - fieldName: email
#        -   name: Application\AppBundle\Entity\OfferTranslation
#            fields:
#                - fieldName: title
#                - fieldName: description
#                - fieldName: url
#                - fieldName: bookingUrl
#        -   name: Application\AppBundle\Entity\Provider
#            fields:
#                - fieldName: title
#                - fieldName: logo
#                - fieldName: email
#                - fieldName: url
#                - fieldName: facebookUrl
#                - fieldName: twitterUrl
#                - fieldName: googlePlusUrl
#        -   name: Application\AppBundle\Entity\ProviderTranslation
#            fields:
#                - fieldName: description