#bd_activity:
#    observed_classes:
#        -   name: Application\Sonata\UserBundle\Entity\User
#            fields:
#                - picture
#                - username
#                - lastLogin
#        -   name: Application\AppBundle\Entity\Offer
#            fields:
#                - icon
#                - email
#        -   name: Application\AppBundle\Entity\OfferTranslation
#            fields:
#                - title
#                - description
#                - url
#                - bookingUrl
#        -   name: Application\AppBundle\Entity\Provider
#            fields:
#                - title
#                - logo
#                - email
#                - url
#                - facebookUrl
#                - twitterUrl
#                - googlePlusUrl
#        -   name: Application\AppBundle\Entity\ProviderTranslation
#            fields:
#                - description