<?php

namespace BrauneDigital\ActivityBundle\Entity\Stream;

/**
 * StreamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StreamRepository extends \Doctrine\ORM\EntityRepository
{
    public function createOrGetFullBackendStream() {
        $streams  = $this->findAll();

        if(sizeof($streams) > 1) {
            throw new \LogicException('In current state we assume a single stream exits. Multiple streams found!');
        } elseif (sizeof($streams) == 0) {
            $backendStream = new Stream();
            $em = $this->_em;

            $em->persist($backendStream);
            $em->flush();

            return $backendStream;
        } else {
            return $streams[0];
        }
    }
}
